const FOOD_CATEGORIES = [
  { id: "burger", name: "汉堡", icon: "🍔" },
  { id: "pizza", name: "披萨", icon: "🍕" },
  { id: "sichuan", name: "川湘", icon: "🌶️" },
  { id: "fast", name: "快餐", icon: "🍱" },
  { id: "huaiyang", name: "淮扬菜", icon: "🥢" },
  { id: "nanjing", name: "南京菜", icon: "🦆" },
  { id: "dongbei", name: "东北菜", icon: "🥘" },
  { id: "hk", name: "港式", icon: "🧋" },
  { id: "noodle", name: "面类", icon: "🍜" },
  { id: "rice_noodle", name: "粉类", icon: "🍲" },
  { id: "dumpling", name: "水饺", icon: "🥟" },
  { id: "snack", name: "烧烤/小吃", icon: "🍢" },
  { id: "light", name: "轻食", icon: "🥗" },
  { id: "hotpot", name: "火锅麻辣烫", icon: "🍲" },
  { id: "drink", name: "饮品甜点", icon: "🧋" }
];

const FOOD_LIST = [
  { id: "mcdonalds_kfc", name: "麦当劳/肯德基", category: "汉堡", icon: "🍔", rating: 5, price: "¥45" },
  { id: "niuyuebao", name: "牛约堡", category: "汉堡", icon: "🍔", rating: 4, price: "¥38" },
  { id: "burger_king", name: "汉堡王", category: "汉堡", icon: "🍔", rating: 4, price: "¥42" },
  { id: "shake_shack", name: "Shake Shack", category: "汉堡", icon: "🍔", rating: 4, price: "¥58" },
  { id: "hot_source", name: "Hot Source", category: "汉堡", icon: "🍔", rating: 4, price: "¥40" },
  { id: "subway", name: "Subway", category: "汉堡", icon: "🥪", rating: 4, price: "¥35" },
  { id: "pizza_hut", name: "必胜客", category: "披萨", icon: "🍕", rating: 5, price: "¥55" },
  { id: "dominos", name: "达美乐", category: "披萨", icon: "🍕", rating: 4, price: "¥52" },
  { id: "mr_pizza", name: "Mr. Pizza", category: "披萨", icon: "🍕", rating: 4, price: "¥58" },
  { id: "erwa", name: "二娃小馆", category: "川湘", icon: "🌶️", rating: 4, price: "¥48" },
  { id: "laoxiangji", name: "老乡鸡", category: "快餐", icon: "🍱", rating: 5, price: "¥35" },
  { id: "laoniangjiu", name: "老娘舅", category: "快餐", icon: "🍱", rating: 4, price: "¥35" },
  { id: "xiangcunji", name: "乡村基", category: "快餐", icon: "🍱", rating: 4, price: "¥32" },
  { id: "chenji_duck_rice", name: "陈记烤鸭饭", category: "淮扬菜", icon: "🦆", rating: 4, price: "¥36" },
  { id: "dongchi", name: "东池便当", category: "快餐", icon: "🍱", rating: 4, price: "¥36" },
  { id: "sanmao_heiyuhua", name: "三猫黑鱼花", category: "川湘", icon: "🐟", rating: 4, price: "¥58" },
  { id: "xuji_suancaiyu", name: "许记酸菜鱼", category: "川湘", icon: "🐟", rating: 4, price: "¥55" },
  { id: "xiaochuniang", name: "小厨娘淮扬菜", category: "淮扬菜", icon: "🥢", rating: 4, price: "¥52" },
  { id: "shiwangfu", name: "狮王府淮扬菜", category: "淮扬菜", icon: "🥢", rating: 4, price: "¥60" },
  { id: "haoji_jinling", name: "好记金陵宴", category: "南京菜", icon: "🦆", rating: 4, price: "¥58" },
  { id: "gaodiede", name: "高嗲嗲湘味爆炒王", category: "川湘", icon: "🌶️", rating: 4, price: "¥48" },
  { id: "bawan", name: "霸碗盖码饭", category: "盖浇饭", icon: "🍚", rating: 4, price: "¥35" },
  { id: "baijia_nanjing", name: "百家小厨南京菜", category: "南京菜", icon: "🦆", rating: 4, price: "¥48" },
  { id: "chinai_curry", name: "池奈咖喱蛋包饭", category: "盖浇饭", icon: "🍛", rating: 4, price: "¥36" },
  { id: "shangguandong", name: "上关东东北菜", category: "东北菜", icon: "🥘", rating: 4, price: "¥45" },
  { id: "nanjing_dapaidang", name: "南京大排档", category: "南京菜", icon: "🦆", rating: 5, price: "¥55" },
  { id: "laotou_gaijiao", name: "老头盖浇饭", category: "盖浇饭", icon: "🍚", rating: 4, price: "¥32" },
  { id: "xinwang", name: "新旺茶餐厅", category: "港式", icon: "🧋", rating: 4, price: "¥55" },
  { id: "yuemingke", name: "粤茗客茶点", category: "港式", icon: "🥢", rating: 4, price: "¥52" },
  { id: "keming", name: "克茗冰室", category: "港式", icon: "🧋", rating: 4, price: "¥45" },
  { id: "lanzhou_noodle", name: "兰州牛肉面", category: "面类", icon: "🍜", rating: 5, price: "¥28" },
  { id: "chongqing_noodle", name: "重庆小面", category: "面类", icon: "🍜", rating: 4, price: "¥25" },
  { id: "pizzahut_western_noodle", name: "必胜客/西堤意面", category: "面类", icon: "🍝", rating: 4, price: "¥45" },
  { id: "qiaoshan_mlx", name: "乔杉衫牛肉米线", category: "粉类", icon: "🍲", rating: 4, price: "¥33" },
  { id: "zhongshi_mlx", name: "仲氏米线", category: "粉类", icon: "🍲", rating: 4, price: "¥30" },
  { id: "pho", name: "越南米线PHO", category: "粉类", icon: "🍲", rating: 4, price: "¥45" },
  { id: "jiming_tangbao", name: "鸡鸣汤包", category: "粉类", icon: "🥟", rating: 4, price: "¥28" },
  { id: "laogulou_tangbao", name: "老鼓楼汤包", category: "粉类", icon: "🥟", rating: 4, price: "¥28" },
  { id: "xianmantang", name: "鲜满堂现浇米线", category: "粉类", icon: "🍲", rating: 4, price: "¥33" },
  { id: "fenxiaozhu", name: "粉小主贵州酸汤牛肉粉", category: "粉类", icon: "🍲", rating: 4, price: "¥35" },
  { id: "yuanji", name: "袁记云饺", category: "水饺", icon: "🥟", rating: 5, price: "¥28" },
  { id: "harbin_dumpling", name: "哈尔滨水饺", category: "水饺", icon: "🥟", rating: 4, price: "¥30" },
  { id: "baoji_bbq", name: "宝记烧烤", category: "烧烤/小吃", icon: "🍢", rating: 4, price: "¥50" },
  { id: "lurenjia", name: "卤人甲鸡爪", category: "烧烤/小吃", icon: "🍗", rating: 4, price: "¥35" },
  { id: "feishu", name: "肥叔锅贴", category: "烧烤/小吃", icon: "🥟", rating: 4, price: "¥28" },
  { id: "pan_fried_chicken", name: "潘老板炸鸡", category: "烧烤/小吃", icon: "🍗", rating: 4, price: "¥38" },
  { id: "salad", name: "轻食沙拉", category: "轻食", icon: "🥗", rating: 3, price: "¥35" },
  { id: "chaoshan_zhou", name: "源香潮汕粥", category: "轻食", icon: "🥣", rating: 4, price: "¥32" },
  { id: "yangguofu", name: "杨国福麻辣烫", category: "火锅麻辣烫", icon: "🍲", rating: 4, price: "¥38" },
  { id: "haidilao_rice", name: "海底捞拌饭", category: "火锅麻辣烫", icon: "🍲", rating: 4, price: "¥36" },
  { id: "bamiaoshuan", name: "八秒涮鲜牛肉火锅", category: "火锅麻辣烫", icon: "🥩", rating: 4, price: "¥58" },
  { id: "heytea", name: "喜茶", category: "饮品甜点", icon: "🧋", rating: 4, price: "¥25" },
  { id: "naixue", name: "奈雪的茶", category: "饮品甜点", icon: "🧋", rating: 4, price: "¥28" },
  { id: "mixue", name: "蜜雪冰城", category: "饮品甜点", icon: "🧋", rating: 4, price: "¥12" },
  { id: "jiushining", name: "就是柠", category: "饮品甜点", icon: "🍋", rating: 4, price: "¥18" },
  { id: "little_blue_cup", name: "小蓝杯", category: "饮品甜点", icon: "☕", rating: 4, price: "¥22" },
  { id: "starbucks", name: "星巴克", category: "饮品甜点", icon: "☕", rating: 4, price: "¥32" },
  { id: "chagee", name: "霸王茶姬", category: "饮品甜点", icon: "🧋", rating: 4, price: "¥22" }
];