const foods=[{name:'麦当劳/肯德基',category:'汉堡',icon:'🍔'},{name:'牛约堡',category:'汉堡',icon:'🍔'},{name:'汉堡王',category:'汉堡',icon:'🍔'},{name:'Shake Shack',category:'汉堡',icon:'🍔'},{name:'Hot Source',category:'汉堡',icon:'🍔'},{name:'Subway',category:'汉堡',icon:'🥪'},{name:'必胜客',category:'披萨',icon:'🍕'},{name:'达美乐',category:'披萨',icon:'🍕'},{name:'Mr. Pizza',category:'披萨',icon:'🍕'},{name:'二娃小馆',category:'川湘',icon:'🌶️'},{name:'老乡鸡',category:'快餐',icon:'🍱'},{name:'老娘舅',category:'快餐',icon:'🍱'},{name:'乡村基',category:'快餐',icon:'🍱'},{name:'陈记烤鸭饭',category:'淮扬菜',icon:'🦆'},{name:'东池便当',category:'快餐',icon:'🍱'},{name:'三猫黑鱼花',category:'川湘',icon:'🐟'},{name:'许记酸菜鱼',category:'川湘',icon:'🐟'},{name:'小厨娘淮扬菜',category:'淮扬菜',icon:'🥘'},{name:'狮王府淮扬菜',category:'淮扬菜',icon:'🥘'},{name:'好记金陵宴',category:'南京菜',icon:'🏮'},{name:'高嗲嗲湘味爆炒王',category:'川湘',icon:'🌶️'},{name:'霸碗盖码饭',category:'盖浇饭',icon:'🍛'},{name:'百家小厨南京菜',category:'南京菜',icon:'🏮'},{name:'池奈咖喱蛋包饭',category:'盖浇饭',icon:'🍛'},{name:'上关东东北菜',category:'东北菜',icon:'🥟'},{name:'南京大排档',category:'南京菜',icon:'🏮'},{name:'老头盖浇饭',category:'盖浇饭',icon:'🍛'},{name:'新旺茶餐厅',category:'港式',icon:'🫖'},{name:'粤茗客茶点',category:'港式',icon:'🥧'},{name:'克茗冰室',category:'港式',icon:'🥤'},{name:'兰州牛肉面',category:'面类',icon:'🍜'},{name:'重庆小面',category:'面类',icon:'🍜'},{name:'必胜客/西堤意面',category:'面类',icon:'🍝'},{name:'乔杉衫牛肉米线',category:'粉类',icon:'🍲'},{name:'仲氏米线',category:'粉类',icon:'🍲'},{name:'越南米线PHO',category:'粉类',icon:'🍲'},{name:'鸡鸣汤包',category:'粉类',icon:'🥟'},{name:'老鼓楼汤包',category:'粉类',icon:'🥟'},{name:'鲜满堂现浇米线',category:'粉类',icon:'🍲'},{name:'粉小主贵州酸汤牛肉粉',category:'粉类',icon:'🍲'},{name:'袁记云饺',category:'水饺',icon:'🥟'},{name:'哈尔滨水饺',category:'水饺',icon:'🥟'},{name:'宝记烧烤',category:'烧烤/小吃',icon:'🍢'},{name:'卤人甲鸡爪',category:'烧烤/小吃',icon:'🍗'},{name:'肥叔锅贴',category:'烧烤/小吃',icon:'🥟'},{name:'潘老板炸鸡',category:'烧烤/小吃',icon:'🍗'},{name:'轻食沙拉',category:'轻食',icon:'🥗'},{name:'源香潮汕粥',category:'轻食',icon:'🥣'},{name:'杨国福麻辣烫',category:'火锅麻辣烫',icon:'🍲'},{name:'海底捞拌饭',category:'火锅麻辣烫',icon:'🍲'},{name:'八秒涮鲜牛肉火锅',category:'火锅麻辣烫',icon:'🥘'},{name:'喜茶',category:'饮品甜点',icon:'🧋'},{name:'奈雪的茶',category:'饮品甜点',icon:'🧋'},{name:'蜜雪冰城',category:'饮品甜点',icon:'🍦'},{name:'就是柠',category:'饮品甜点',icon:'🍋'},{name:'小蓝杯',category:'饮品甜点',icon:'☕'},{name:'星巴克',category:'饮品甜点',icon:'☕'},{name:'霸王茶姬',category:'饮品甜点',icon:'🧋'}];
const icons={汉堡:'🍔',披萨:'🍕',川湘:'🌶️',快餐:'🍱',淮扬菜:'🥘',南京菜:'🏮',盖浇饭:'🍛',东北菜:'🥟',港式:'🫖',面类:'🍜',粉类:'🍲',水饺:'🥟','烧烤/小吃':'🍢',轻食:'🥗',火锅麻辣烫:'🍲',饮品甜点:'🧋'};
const cats=[...new Set(foods.map(f=>f.category))];let step=1,want=[],notWant=[],pool=[],champ=null,i=1,lastPool=[];const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function renderCats(mode){const g=$('categoryGrid');g.innerHTML='';cats.forEach(c=>{const b=document.createElement('button');b.className='category-card';b.dataset.cat=c;b.innerHTML='<span class="icon">'+(icons[c]||'🍽️')+'</span><span>'+c+'</span>';b.onclick=()=>b.classList.toggle(mode==='exclude'?'excluded':'selected');g.appendChild(b)})}
function selected(){return [...document.querySelectorAll('.category-card.selected,.category-card.excluded')].map(x=>x.dataset.cat)}
function startSetup(){step=1;want=[];notWant=[];$('setupEyebrow').textContent='STEP 1';$('setupTitle').textContent='今天想吃什么？';$('setupNextBtn').textContent='继续 →';$('setupMessage').textContent='';renderCats('want');show('setupScreen')}
function nextSetup(){const s=selected();if(step===1){if(!s.length){$('setupMessage').textContent='至少选一个分类';return}want=s;step=2;$('setupEyebrow').textContent='STEP 2';$('setupTitle').textContent='今天绝对不要吃什么？';$('setupNextBtn').textContent='开始 Battle!';$('setupMessage').textContent='';renderCats('exclude');return}notWant=s;pool=foods.filter(f=>want.includes(f.category)&&!notWant.includes(f.category));lastPool=[...pool];if(pool.length<2){$('setupMessage').textContent='候选太少了，多选几个分类吧';return}champ=pool[0];i=1;show('battleScreen');renderBattle()}
function card(f,label){return '<span class="card-label">'+label+'</span><div><div class="food-icon">'+f.icon+'</div><div class="food-name">'+f.name+'</div><div class="food-category">'+f.category+'</div></div>'}
function renderBattle(){const ch=pool[i];$('roundLabel').textContent='Round '+i+' / '+(pool.length-1);$('progressBar').style.width=Math.round((i-1)/(pool.length-1)*100)+'%';$('championCard').className='battle-card';$('challengerCard').className='battle-card';$('championCard').innerHTML=card(champ,'当前冠军');$('challengerCard').innerHTML=card(ch,'挑战者')}
function choose(kind){const challenger=pool[i];const winner=kind==='champ'?champ:challenger;const loser=kind==='champ'?'challengerCard':'championCard';$(loser).classList.add('reject','slash');setTimeout(()=>{champ=winner;i++;if(i>=pool.length){finish()}else{renderBattle()}},650)}
function finishNow(){finish()}
function save(f){let h=JSON.parse(localStorage.getItem('ffb_history')||'[]');let c=JSON.parse(localStorage.getItem('ffb_counts')||'{}');let d=new Date().toISOString().slice(0,10);h.unshift({date:d,name:f.name,icon:f.icon,category:f.category});h=h.slice(0,30);c[f.name]=(c[f.name]||0)+1;localStorage.setItem('ffb_history',JSON.stringify(h));localStorage.setItem('ffb_counts',JSON.stringify(c))}
function finish(){save(champ);$('championIcon').textContent=champ.icon;$('championName').textContent=champ.name;show('championScreen')}
function hall(){let c=JSON.parse(localStorage.getItem('ffb_counts')||'{}');let a=Object.entries(c).sort((x,y)=>y[1]-x[1]);$('hallList').innerHTML=a.length?'':'<p class="empty">还没有冠军。</p>';a.forEach((r,n)=>{$('hallList').innerHTML+='<div class="rank-item"><b>'+(n+1)+'. '+r[0]+'</b><span>'+r[1]+' 冠</span></div>'});show('hallScreen')}
function record(){let h=JSON.parse(localStorage.getItem('ffb_history')||'[]');$('recordList').innerHTML=h.length?'':'<p class="empty">还没有记录。</p>';h.slice(0,12).forEach(x=>{$('recordList').innerHTML+='<div class="record-item"><b>'+x.icon+' '+x.name+'</b><span>'+x.date+'</span></div>'});show('recordScreen')}
function foodList(){let box=$('foodList');box.innerHTML='';foods.forEach(f=>box.innerHTML+='<div class="food-row"><b>'+f.icon+' '+f.name+'</b><span>'+f.category+'</span></div>');show('foodListScreen')}
function wheel(){show('wheelScreen');$('wheelText').textContent=lastPool.length?'从本次候选里抽一个':'先开始 Battle 选择分类'}
function spin(){let a=lastPool.length?lastPool:foods;champ=a[Math.floor(Math.random()*a.length)];$('wheel').style.transform='rotate('+(1080+Math.random()*720)+'deg)';setTimeout(finish,1200)}
$('startBattleBtn').onclick=startSetup;$('setupNextBtn').onclick=nextSetup;$('setupBackBtn').onclick=()=>show('homeScreen');$('battleBackBtn').onclick=()=>show('setupScreen');$('championCard').onclick=()=>choose('champ');$('challengerCard').onclick=()=>choose('challenger');$('keepChampionBtn').onclick=finishNow;$('chooseChallengerBtn').onclick=()=>choose('challenger');$('againBtn').onclick=startSetup;$('homeBtn').onclick=()=>show('homeScreen');$('favBtn').onclick=()=>$('streakText').textContent='已收藏 ❤️';$('championHallBtn').onclick=hall;$('battleRecordBtn').onclick=record;$('foodListBtn').onclick=foodList;$('luckyWheelBtn').onclick=wheel;$('spinBtn').onclick=spin;$('wheelBackBtn').onclick=()=>show('homeScreen');$('hallBackBtn').onclick=()=>show('homeScreen');$('recordBackBtn').onclick=()=>show('homeScreen');$('foodListBackBtn').onclick=()=>show('homeScreen');$('settingsBtn').onclick=()=>{};